"""Genrate a DYRAD page."""
import locale
locale.setlocale(locale.LC_ALL, 'C')

def gen_a_row():
    """Randomize a str of letters."""
    import secrets
    import string

    alphabet = string.ascii_uppercase[0:-1]
    row = ''

    while len(alphabet) != 0:
        letter = secrets.choice(alphabet)
        row += letter
        alphabet = alphabet.replace(letter, '')

    return row


def row_dict(row):
    """Split row into cells."""
    row = {
        'c0': row[0:4],
        'c1': row[4:7],
        'c2': row[7:10],
        'c3': row[10:12],
        'c4': row[12:14],
        'c5': row[14:17],
        'c6': row[17:19],
        'c7': row[19:21],
        'c8': row[21:23],
        'c9': row[23:25],
    }
    return row

rowA = row_dict(gen_a_row())
rowB = row_dict(gen_a_row())
rowC = row_dict(gen_a_row())
rowD = row_dict(gen_a_row())
rowE = row_dict(gen_a_row())
rowF = row_dict(gen_a_row())
rowG = row_dict(gen_a_row())
rowH = row_dict(gen_a_row())
rowI = row_dict(gen_a_row())
rowJ = row_dict(gen_a_row())
rowK = row_dict(gen_a_row())
rowL = row_dict(gen_a_row())
rowM = row_dict(gen_a_row())
rowN = row_dict(gen_a_row())
rowO = row_dict(gen_a_row())
rowP = row_dict(gen_a_row())
rowQ = row_dict(gen_a_row())
rowR = row_dict(gen_a_row())
rowS = row_dict(gen_a_row())
rowT = row_dict(gen_a_row())
rowU = row_dict(gen_a_row())
rowV = row_dict(gen_a_row())
rowW = row_dict(gen_a_row())
rowX = row_dict(gen_a_row())
rowY = row_dict(gen_a_row())

bcst01 = gen_a_row()
bcst02 = gen_a_row()
bcst03 = gen_a_row()
bcst04 = gen_a_row()
bcst05 = gen_a_row()
bcst06 = gen_a_row()
bcst07 = gen_a_row()
bcst08 = gen_a_row()

bcst11 = gen_a_row()
bcst12 = gen_a_row()
bcst13 = gen_a_row()
bcst14 = gen_a_row()
bcst15 = gen_a_row()
bcst16 = gen_a_row()
bcst17 = gen_a_row()
bcst18 = gen_a_row()

beg = '190000Z SEP 20'
end = '192359Z SEP 20'

f = open('dryad.html', 'w',  encoding='utf_8_sig')
print("<html><head>", file=f)
print("<style>", file=f)
print("body { font-family: monospace; }", file=f)
print("td { padding-right: 8pt; }", file=f)
print(".cent { text-align: center; }", file=f)
print(".bold { font-weight: bold; }", file=f)
print("</style>", file=f)
print("</head><body>", file=f)

print("<p><b>Valid:</b> {} <b>/</b> {}</p>".format(beg, end), file=f)
print("<hr/>", file=f)

print("<p><b>DRYAD Cipher Sheet</b></p>", file=f)

print("<table><tbody>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> A</td>", file=f)
print("<td>{}</td>".format(rowA['c0']), file=f)
print("<td>{}</td>".format(rowA['c1']), file=f)
print("<td>{}</td>".format(rowA['c2']), file=f)
print("<td>{}</td>".format(rowA['c3']), file=f)
print("<td>{}</td>".format(rowA['c4']), file=f)
print("<td>{}</td>".format(rowA['c5']), file=f)
print("<td>{}</td>".format(rowA['c6']), file=f)
print("<td>{}</td>".format(rowA['c7']), file=f)
print("<td>{}</td>".format(rowA['c8']), file=f)
print("<td>{}</td>".format(rowA['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> B</td>", file=f)
print("<td>{}</td>".format(rowB['c0']), file=f)
print("<td>{}</td>".format(rowB['c1']), file=f)
print("<td>{}</td>".format(rowB['c2']), file=f)
print("<td>{}</td>".format(rowB['c3']), file=f)
print("<td>{}</td>".format(rowB['c4']), file=f)
print("<td>{}</td>".format(rowB['c5']), file=f)
print("<td>{}</td>".format(rowB['c6']), file=f)
print("<td>{}</td>".format(rowB['c7']), file=f)
print("<td>{}</td>".format(rowB['c8']), file=f)
print("<td>{}</td>".format(rowB['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> C</td>", file=f)
print("<td>{}</td>".format(rowC['c0']), file=f)
print("<td>{}</td>".format(rowC['c1']), file=f)
print("<td>{}</td>".format(rowC['c2']), file=f)
print("<td>{}</td>".format(rowC['c3']), file=f)
print("<td>{}</td>".format(rowC['c4']), file=f)
print("<td>{}</td>".format(rowC['c5']), file=f)
print("<td>{}</td>".format(rowC['c6']), file=f)
print("<td>{}</td>".format(rowC['c7']), file=f)
print("<td>{}</td>".format(rowC['c8']), file=f)
print("<td>{}</td>".format(rowC['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> D</td>", file=f)
print("<td>{}</td>".format(rowD['c0']), file=f)
print("<td>{}</td>".format(rowD['c1']), file=f)
print("<td>{}</td>".format(rowD['c2']), file=f)
print("<td>{}</td>".format(rowD['c3']), file=f)
print("<td>{}</td>".format(rowD['c4']), file=f)
print("<td>{}</td>".format(rowD['c5']), file=f)
print("<td>{}</td>".format(rowD['c6']), file=f)
print("<td>{}</td>".format(rowD['c7']), file=f)
print("<td>{}</td>".format(rowD['c8']), file=f)
print("<td>{}</td>".format(rowD['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> E</td>", file=f)
print("<td>{}</td>".format(rowE['c0']), file=f)
print("<td>{}</td>".format(rowE['c1']), file=f)
print("<td>{}</td>".format(rowE['c2']), file=f)
print("<td>{}</td>".format(rowE['c3']), file=f)
print("<td>{}</td>".format(rowE['c4']), file=f)
print("<td>{}</td>".format(rowE['c5']), file=f)
print("<td>{}</td>".format(rowE['c6']), file=f)
print("<td>{}</td>".format(rowE['c7']), file=f)
print("<td>{}</td>".format(rowE['c8']), file=f)
print("<td>{}</td>".format(rowE['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> F</td>", file=f)
print("<td>{}</td>".format(rowF['c0']), file=f)
print("<td>{}</td>".format(rowF['c1']), file=f)
print("<td>{}</td>".format(rowF['c2']), file=f)
print("<td>{}</td>".format(rowF['c3']), file=f)
print("<td>{}</td>".format(rowF['c4']), file=f)
print("<td>{}</td>".format(rowF['c5']), file=f)
print("<td>{}</td>".format(rowF['c6']), file=f)
print("<td>{}</td>".format(rowF['c7']), file=f)
print("<td>{}</td>".format(rowF['c8']), file=f)
print("<td>{}</td>".format(rowF['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> G</td>", file=f)
print("<td>{}</td>".format(rowG['c0']), file=f)
print("<td>{}</td>".format(rowG['c1']), file=f)
print("<td>{}</td>".format(rowG['c2']), file=f)
print("<td>{}</td>".format(rowG['c3']), file=f)
print("<td>{}</td>".format(rowG['c4']), file=f)
print("<td>{}</td>".format(rowG['c5']), file=f)
print("<td>{}</td>".format(rowG['c6']), file=f)
print("<td>{}</td>".format(rowG['c7']), file=f)
print("<td>{}</td>".format(rowG['c8']), file=f)
print("<td>{}</td>".format(rowG['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> H</td>", file=f)
print("<td>{}</td>".format(rowH['c0']), file=f)
print("<td>{}</td>".format(rowH['c1']), file=f)
print("<td>{}</td>".format(rowH['c2']), file=f)
print("<td>{}</td>".format(rowH['c3']), file=f)
print("<td>{}</td>".format(rowH['c4']), file=f)
print("<td>{}</td>".format(rowH['c5']), file=f)
print("<td>{}</td>".format(rowH['c6']), file=f)
print("<td>{}</td>".format(rowH['c7']), file=f)
print("<td>{}</td>".format(rowH['c8']), file=f)
print("<td>{}</td>".format(rowH['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> I</td>", file=f)
print("<td>{}</td>".format(rowI['c0']), file=f)
print("<td>{}</td>".format(rowI['c1']), file=f)
print("<td>{}</td>".format(rowI['c2']), file=f)
print("<td>{}</td>".format(rowI['c3']), file=f)
print("<td>{}</td>".format(rowI['c4']), file=f)
print("<td>{}</td>".format(rowI['c5']), file=f)
print("<td>{}</td>".format(rowI['c6']), file=f)
print("<td>{}</td>".format(rowI['c7']), file=f)
print("<td>{}</td>".format(rowI['c8']), file=f)
print("<td>{}</td>".format(rowI['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> J</td>", file=f)
print("<td>{}</td>".format(rowJ['c0']), file=f)
print("<td>{}</td>".format(rowJ['c1']), file=f)
print("<td>{}</td>".format(rowJ['c2']), file=f)
print("<td>{}</td>".format(rowJ['c3']), file=f)
print("<td>{}</td>".format(rowJ['c4']), file=f)
print("<td>{}</td>".format(rowJ['c5']), file=f)
print("<td>{}</td>".format(rowJ['c6']), file=f)
print("<td>{}</td>".format(rowJ['c7']), file=f)
print("<td>{}</td>".format(rowJ['c8']), file=f)
print("<td>{}</td>".format(rowJ['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> K</td>", file=f)
print("<td>{}</td>".format(rowK['c0']), file=f)
print("<td>{}</td>".format(rowK['c1']), file=f)
print("<td>{}</td>".format(rowK['c2']), file=f)
print("<td>{}</td>".format(rowK['c3']), file=f)
print("<td>{}</td>".format(rowK['c4']), file=f)
print("<td>{}</td>".format(rowK['c5']), file=f)
print("<td>{}</td>".format(rowK['c6']), file=f)
print("<td>{}</td>".format(rowK['c7']), file=f)
print("<td>{}</td>".format(rowK['c8']), file=f)
print("<td>{}</td>".format(rowK['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> L</td>", file=f)
print("<td>{}</td>".format(rowL['c0']), file=f)
print("<td>{}</td>".format(rowL['c1']), file=f)
print("<td>{}</td>".format(rowL['c2']), file=f)
print("<td>{}</td>".format(rowL['c3']), file=f)
print("<td>{}</td>".format(rowL['c4']), file=f)
print("<td>{}</td>".format(rowL['c5']), file=f)
print("<td>{}</td>".format(rowL['c6']), file=f)
print("<td>{}</td>".format(rowL['c7']), file=f)
print("<td>{}</td>".format(rowL['c8']), file=f)
print("<td>{}</td>".format(rowL['c9']), file=f)
print("</tr>", file=f)


print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> M</td>", file=f)
print("<td>{}</td>".format(rowM['c0']), file=f)
print("<td>{}</td>".format(rowM['c1']), file=f)
print("<td>{}</td>".format(rowM['c2']), file=f)
print("<td>{}</td>".format(rowM['c3']), file=f)
print("<td>{}</td>".format(rowM['c4']), file=f)
print("<td>{}</td>".format(rowM['c5']), file=f)
print("<td>{}</td>".format(rowM['c6']), file=f)
print("<td>{}</td>".format(rowM['c7']), file=f)
print("<td>{}</td>".format(rowM['c8']), file=f)
print("<td>{}</td>".format(rowM['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> N</td>", file=f)
print("<td>{}</td>".format(rowN['c0']), file=f)
print("<td>{}</td>".format(rowN['c1']), file=f)
print("<td>{}</td>".format(rowN['c2']), file=f)
print("<td>{}</td>".format(rowN['c3']), file=f)
print("<td>{}</td>".format(rowN['c4']), file=f)
print("<td>{}</td>".format(rowN['c5']), file=f)
print("<td>{}</td>".format(rowN['c6']), file=f)
print("<td>{}</td>".format(rowN['c7']), file=f)
print("<td>{}</td>".format(rowN['c8']), file=f)
print("<td>{}</td>".format(rowN['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> O</td>", file=f)
print("<td>{}</td>".format(rowO['c0']), file=f)
print("<td>{}</td>".format(rowO['c1']), file=f)
print("<td>{}</td>".format(rowO['c2']), file=f)
print("<td>{}</td>".format(rowO['c3']), file=f)
print("<td>{}</td>".format(rowO['c4']), file=f)
print("<td>{}</td>".format(rowO['c5']), file=f)
print("<td>{}</td>".format(rowO['c6']), file=f)
print("<td>{}</td>".format(rowO['c7']), file=f)
print("<td>{}</td>".format(rowO['c8']), file=f)
print("<td>{}</td>".format(rowO['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> P</td>", file=f)
print("<td>{}</td>".format(rowP['c0']), file=f)
print("<td>{}</td>".format(rowP['c1']), file=f)
print("<td>{}</td>".format(rowP['c2']), file=f)
print("<td>{}</td>".format(rowP['c3']), file=f)
print("<td>{}</td>".format(rowP['c4']), file=f)
print("<td>{}</td>".format(rowP['c5']), file=f)
print("<td>{}</td>".format(rowP['c6']), file=f)
print("<td>{}</td>".format(rowP['c7']), file=f)
print("<td>{}</td>".format(rowP['c8']), file=f)
print("<td>{}</td>".format(rowP['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> Q</td>", file=f)
print("<td>{}</td>".format(rowQ['c0']), file=f)
print("<td>{}</td>".format(rowQ['c1']), file=f)
print("<td>{}</td>".format(rowQ['c2']), file=f)
print("<td>{}</td>".format(rowQ['c3']), file=f)
print("<td>{}</td>".format(rowQ['c4']), file=f)
print("<td>{}</td>".format(rowQ['c5']), file=f)
print("<td>{}</td>".format(rowQ['c6']), file=f)
print("<td>{}</td>".format(rowQ['c7']), file=f)
print("<td>{}</td>".format(rowQ['c8']), file=f)
print("<td>{}</td>".format(rowQ['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> R</td>", file=f)
print("<td>{}</td>".format(rowR['c0']), file=f)
print("<td>{}</td>".format(rowR['c1']), file=f)
print("<td>{}</td>".format(rowR['c2']), file=f)
print("<td>{}</td>".format(rowR['c3']), file=f)
print("<td>{}</td>".format(rowR['c4']), file=f)
print("<td>{}</td>".format(rowR['c5']), file=f)
print("<td>{}</td>".format(rowR['c6']), file=f)
print("<td>{}</td>".format(rowR['c7']), file=f)
print("<td>{}</td>".format(rowR['c8']), file=f)
print("<td>{}</td>".format(rowR['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> S</td>", file=f)
print("<td>{}</td>".format(rowS['c0']), file=f)
print("<td>{}</td>".format(rowS['c1']), file=f)
print("<td>{}</td>".format(rowS['c2']), file=f)
print("<td>{}</td>".format(rowS['c3']), file=f)
print("<td>{}</td>".format(rowS['c4']), file=f)
print("<td>{}</td>".format(rowS['c5']), file=f)
print("<td>{}</td>".format(rowS['c6']), file=f)
print("<td>{}</td>".format(rowS['c7']), file=f)
print("<td>{}</td>".format(rowS['c8']), file=f)
print("<td>{}</td>".format(rowS['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> T</td>", file=f)
print("<td>{}</td>".format(rowT['c0']), file=f)
print("<td>{}</td>".format(rowT['c1']), file=f)
print("<td>{}</td>".format(rowT['c2']), file=f)
print("<td>{}</td>".format(rowT['c3']), file=f)
print("<td>{}</td>".format(rowT['c4']), file=f)
print("<td>{}</td>".format(rowT['c5']), file=f)
print("<td>{}</td>".format(rowT['c6']), file=f)
print("<td>{}</td>".format(rowT['c7']), file=f)
print("<td>{}</td>".format(rowT['c8']), file=f)
print("<td>{}</td>".format(rowT['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> U</td>", file=f)
print("<td>{}</td>".format(rowU['c0']), file=f)
print("<td>{}</td>".format(rowU['c1']), file=f)
print("<td>{}</td>".format(rowU['c2']), file=f)
print("<td>{}</td>".format(rowU['c3']), file=f)
print("<td>{}</td>".format(rowU['c4']), file=f)
print("<td>{}</td>".format(rowU['c5']), file=f)
print("<td>{}</td>".format(rowU['c6']), file=f)
print("<td>{}</td>".format(rowU['c7']), file=f)
print("<td>{}</td>".format(rowU['c8']), file=f)
print("<td>{}</td>".format(rowU['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> V</td>", file=f)
print("<td>{}</td>".format(rowV['c0']), file=f)
print("<td>{}</td>".format(rowV['c1']), file=f)
print("<td>{}</td>".format(rowV['c2']), file=f)
print("<td>{}</td>".format(rowV['c3']), file=f)
print("<td>{}</td>".format(rowV['c4']), file=f)
print("<td>{}</td>".format(rowV['c5']), file=f)
print("<td>{}</td>".format(rowV['c6']), file=f)
print("<td>{}</td>".format(rowV['c7']), file=f)
print("<td>{}</td>".format(rowV['c8']), file=f)
print("<td>{}</td>".format(rowV['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> W</td>", file=f)
print("<td>{}</td>".format(rowW['c0']), file=f)
print("<td>{}</td>".format(rowW['c1']), file=f)
print("<td>{}</td>".format(rowW['c2']), file=f)
print("<td>{}</td>".format(rowW['c3']), file=f)
print("<td>{}</td>".format(rowW['c4']), file=f)
print("<td>{}</td>".format(rowW['c5']), file=f)
print("<td>{}</td>".format(rowW['c6']), file=f)
print("<td>{}</td>".format(rowW['c7']), file=f)
print("<td>{}</td>".format(rowW['c8']), file=f)
print("<td>{}</td>".format(rowW['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> X</td>", file=f)
print("<td>{}</td>".format(rowX['c0']), file=f)
print("<td>{}</td>".format(rowX['c1']), file=f)
print("<td>{}</td>".format(rowX['c2']), file=f)
print("<td>{}</td>".format(rowX['c3']), file=f)
print("<td>{}</td>".format(rowX['c4']), file=f)
print("<td>{}</td>".format(rowX['c5']), file=f)
print("<td>{}</td>".format(rowX['c6']), file=f)
print("<td>{}</td>".format(rowX['c7']), file=f)
print("<td>{}</td>".format(rowX['c8']), file=f)
print("<td>{}</td>".format(rowX['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> Y</td>", file=f)
print("<td>{}</td>".format(rowY['c0']), file=f)
print("<td>{}</td>".format(rowY['c1']), file=f)
print("<td>{}</td>".format(rowY['c2']), file=f)
print("<td>{}</td>".format(rowY['c3']), file=f)
print("<td>{}</td>".format(rowY['c4']), file=f)
print("<td>{}</td>".format(rowY['c5']), file=f)
print("<td>{}</td>".format(rowY['c6']), file=f)
print("<td>{}</td>".format(rowY['c7']), file=f)
print("<td>{}</td>".format(rowY['c8']), file=f)
print("<td>{}</td>".format(rowY['c9']), file=f)
print("</tr>", file=f)

print("</tbody></table>", file=f)
print("<hr/>", file=f)
print("<p><b>Broadcast Authorizations</b></p>", file=f)

print("<table><tbody>", file=f)
print("<tr>", file=f)
print("<td>{}</td>".format(bcst01[:4]), file=f)
print("<td>{}</td>".format(bcst02[:4]), file=f)
print("<td>{}</td>".format(bcst03[:4]), file=f)
print("<td>{}</td>".format(bcst04[:4]), file=f)
print("<td>{}</td>".format(bcst05[:4]), file=f)
print("<td>{}</td>".format(bcst06[:4]), file=f)
print("<td>{}</td>".format(bcst07[:4]), file=f)
print("<td>{}</td>".format(bcst08[:4]), file=f)
print("</tr>", file=f)
print("<tr>", file=f)
print("<td>{}</td>".format(bcst11[:4]), file=f)
print("<td>{}</td>".format(bcst12[:4]), file=f)
print("<td>{}</td>".format(bcst13[:4]), file=f)
print("<td>{}</td>".format(bcst14[:4]), file=f)
print("<td>{}</td>".format(bcst15[:4]), file=f)
print("<td>{}</td>".format(bcst16[:4]), file=f)
print("<td>{}</td>".format(bcst17[:4]), file=f)
print("<td>{}</td>".format(bcst18[:4]), file=f)
print("</tr>", file=f)
print("</tbody></table>", file=f)
print("</body></html>", file=f)
f.close()
