"""Genrate a DYRAD page."""
import locale
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--begin', type=str, dest='begin', default='990000 ABC 99')
parser.add_argument('--end', type=str, dest='end', default='992359 ABC 99')
args = parser.parse_args()

locale.setlocale(locale.LC_ALL, 'C')

def gen_a_row():
    """Randomize a str of letters."""
    import secrets
    import string

    alphabet = string.ascii_uppercase[0:-1]
    row = ''

    while len(alphabet) != 0:
        letter = secrets.choice(alphabet)
        row += letter
        alphabet = alphabet.replace(letter, '')

    return row


def row_dict(row):
    """Split row into cells."""
    row = {
        'c0': row[0:4],
        'c1': row[4:7],
        'c2': row[7:10],
        'c3': row[10:12],
        'c4': row[12:14],
        'c5': row[14:17],
        'c6': row[17:19],
        'c7': row[19:21],
        'c8': row[21:23],
        'c9': row[23:25],
    }
    return row

DryadRows = 'ABCDEFGHIJKLMNOPQRSTUVWXY'

BcstRows = list(range(1,9)) + list(range(11,19))

DryadDict = {}
BcstDict = {}

for row in DryadRows:
    DryadDict[row] = row_dict(gen_a_row())

for row in BcstRows:
    BcstDict[row] = gen_a_row()

f = open('dryad.html', 'w',  encoding='utf_8_sig')
print("<html><head>", file=f)
print("<style>", file=f)
print("body { font-family: monospace; }", file=f)
print("td { padding-right: 8pt; }", file=f)
print(".cent { text-align: center; }", file=f)
print(".bold { font-weight: bold; }", file=f)
print("</style>", file=f)
print("</head><body>", file=f) 

print("<p><b>Valid:</b> {} <b>/</b> {}</p>".format(
    args.begin, args.end), file=f)
print("<hr/>", file=f)

print("<p><b>DRYAD Cipher Sheet</b></p>", file=f)

print("<table><tbody>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> A</td>", file=f)
print("<td>{}</td>".format(DryadDict['A']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['A']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> B</td>", file=f)
print("<td>{}</td>".format(DryadDict['B']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['B']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> C</td>", file=f)
print("<td>{}</td>".format(DryadDict['C']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['C']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> D</td>", file=f)
print("<td>{}</td>".format(DryadDict['D']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['D']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> E</td>", file=f)
print("<td>{}</td>".format(DryadDict['E']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['E']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> F</td>", file=f)
print("<td>{}</td>".format(DryadDict['F']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['F']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> G</td>", file=f)
print("<td>{}</td>".format(DryadDict['G']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['G']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> H</td>", file=f)
print("<td>{}</td>".format(DryadDict['H']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['H']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> I</td>", file=f)
print("<td>{}</td>".format(DryadDict['I']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['I']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> J</td>", file=f)
print("<td>{}</td>".format(DryadDict['J']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['J']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> K</td>", file=f)
print("<td>{}</td>".format(DryadDict['K']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['K']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> L</td>", file=f)
print("<td>{}</td>".format(DryadDict['L']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['L']['c9']), file=f)
print("</tr>", file=f)


print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> M</td>", file=f)
print("<td>{}</td>".format(DryadDict['M']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['M']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> N</td>", file=f)
print("<td>{}</td>".format(DryadDict['N']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['N']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> O</td>", file=f)
print("<td>{}</td>".format(DryadDict['O']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['O']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> P</td>", file=f)
print("<td>{}</td>".format(DryadDict['P']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['P']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> Q</td>", file=f)
print("<td>{}</td>".format(DryadDict['Q']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['Q']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> R</td>", file=f)
print("<td>{}</td>".format(DryadDict['R']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['R']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"bold\"> ABC</td>", file=f)
print("<td class=\"bold\">DEF</td>", file=f)
print("<td class=\"bold\">GHJ</td>", file=f)
print("<td class=\"bold\">KL</td>", file=f)
print("<td class=\"bold\">MN</td>", file=f)
print("<td class=\"bold\">PQR</td>", file=f)
print("<td class=\"bold\">ST</td>", file=f)
print("<td class=\"bold\">UV</td>", file=f)
print("<td class=\"bold\">WX</td>", file=f)
print("<td class=\"bold\">YZ</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td></td>", file=f)
print("<td class=\"cent bold\">0</td>", file=f)
print("<td class=\"cent bold\">1</td>", file=f)
print("<td class=\"cent bold\">2</td>", file=f)
print("<td class=\"cent bold\">3</td>", file=f)
print("<td class=\"cent bold\">4</td>", file=f)
print("<td class=\"cent bold\">5</td>", file=f)
print("<td class=\"cent bold\">6</td>", file=f)
print("<td class=\"cent bold\">7</td>", file=f)
print("<td class=\"cent bold\">8</td>", file=f)
print("<td class=\"cent bold\">9</td>", file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> S</td>", file=f)
print("<td>{}</td>".format(DryadDict['S']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['S']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> T</td>", file=f)
print("<td>{}</td>".format(DryadDict['T']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['T']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> U</td>", file=f)
print("<td>{}</td>".format(DryadDict['U']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['U']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> V</td>", file=f)
print("<td>{}</td>".format(DryadDict['V']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['V']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> W</td>", file=f)
print("<td>{}</td>".format(DryadDict['W']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['W']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> X</td>", file=f)
print("<td>{}</td>".format(DryadDict['X']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['X']['c9']), file=f)
print("</tr>", file=f)

print("<tr>", file=f)
print("<td class=\"bold\"> Y</td>", file=f)
print("<td>{}</td>".format(DryadDict['Y']['c0']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c1']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c2']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c3']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c4']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c5']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c6']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c7']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c8']), file=f)
print("<td>{}</td>".format(DryadDict['Y']['c9']), file=f)
print("</tr>", file=f)

print("</tbody></table>", file=f)
print("<hr/>", file=f)
print("<p><b>Broadcast Authorizations</b></p>", file=f)

print("<table><tbody>", file=f)
print("<tr>", file=f)
print("<td>{}</td>".format(BcstDict[1][:4]), file=f)
print("<td>{}</td>".format(BcstDict[2][:4]), file=f)
print("<td>{}</td>".format(BcstDict[3][:4]), file=f)
print("<td>{}</td>".format(BcstDict[4][:4]), file=f)
print("<td>{}</td>".format(BcstDict[5][:4]), file=f)
print("<td>{}</td>".format(BcstDict[6][:4]), file=f)
print("<td>{}</td>".format(BcstDict[7][:4]), file=f)
print("<td>{}</td>".format(BcstDict[8][:4]), file=f)
print("</tr>", file=f)
print("<tr>", file=f)
print("<td>{}</td>".format(BcstDict[11][:4]), file=f)
print("<td>{}</td>".format(BcstDict[12][:4]), file=f)
print("<td>{}</td>".format(BcstDict[13][:4]), file=f)
print("<td>{}</td>".format(BcstDict[14][:4]), file=f)
print("<td>{}</td>".format(BcstDict[15][:4]), file=f)
print("<td>{}</td>".format(BcstDict[16][:4]), file=f)
print("<td>{}</td>".format(BcstDict[17][:4]), file=f)
print("<td>{}</td>".format(BcstDict[18][:4]), file=f)
print("</tr>", file=f)
print("</tbody></table>", file=f)
print("</body></html>", file=f)
f.close()
